[package]
name = "noita-black-hole-sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.14.0"
libm = "0.2.15"
rand = "0.9.1"
sdl2 = {version = "0.38.0", features = ["image"] }
